# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-11 20:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='conected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_date_conected',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 20, 22, 48, 149000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
